### ISSUE TITLE
why is it empty

### ISSUE THREAD

**Issue by dusjagr** [kasbah/svg2sz-fosdem19#1]
[spirale.zip](https://github.com/kasbah/svg2sz-fosdem19/files/2830078/spirale.zip)

**Comment by dusjagr** [comment]
![selection_999 384](https://user-images.githubusercontent.com/357542/52242406-e9139d80-28d6-11e9-941a-87c3e26f7512.png)

**Comment by kasbah** [comment]
You already made a shanzai copy? Good thing, I actually didn't save my SVG from the talk. The copycat ecosystem works!  :cat:   (did you see [Niibe's talk](https://fosdem.org/2019/schedule/event/gnuk_hardware/)  btw?)
